### ISSUE TITLE
Method for indenting multi-line arguments

### ISSUE THREAD

**Issue by jzaefferer** [millermedeiros/rocambole-indent#3]
Similar to my other comment about updating comments, I'd also like to use this module to replace [this logic](https://github.com/jzaefferer/esformatter-jquery-chain/blob/75e9f178eb0a68223ccdfcf6fef7fe74d5f0557d/plugin.js#L71-L85). For some context, it deals with this:

Input:
```js
toShow
	.attr( "aria-hidden", "false" )
	.prev()
	.attr( {
		"aria-selected": "true",
		"aria-expanded": "true",
		tabIndex: 0
	} );
```

Bad output:
```js
toShow
	.attr( "aria-hidden", "false" )
	.prev()
		.attr( {
		"aria-selected": "true",
		"aria-expanded": "true",
		tabIndex: 0
	} );
```

Good output:
```js
toShow
	.attr( "aria-hidden", "false" )
	.prev()
		.attr( {
			"aria-selected": "true",
			"aria-expanded": "true",
			tabIndex: 0
		} );
```

Maybe `inBetween()` can be used for this, but I'm not sure how.

**Comment by millermedeiros** [comment]
you could call `inBetween` passing the closing parenthesis of `prev()` until closing parenthesis of `attr()` to get the expected behavior.

**Comment by jzaefferer** [comment]
Thanks for the input, I got it working! I'm now using `inBetween()` (not quite as suggested, but close enough), `addLevel()` and `alignComments(node)`. There might be more potential for simplifying: https://github.com/jzaefferer/esformatter-jquery-chain/commit/82990d23d4b21dfafce458cc6cbe01f3bb0ac815

Should be a lot more reliable than my custom logic that has seen only limited testing. And I can benefit from future improvements of this module.
